version: '3.3'

services:
  envoyer:
    container_name: envoyer
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - envoyer_db:/var/lib/mysql
      - envoyer_rabbitmq:/var/lib/rabbitmq
    ports:
      - "3000:3000"
      - "8081:8081"
      - "15672:15672"
      - "3306:3306"
    environment:
      GOPATH: /go/
    tty: true

volumes:
  envoyer_db:
  envoyer_rabbitmq: