import Head from 'next/head';
import CardSettings from '@/components/CardSettings';
import Admin from '@/layouts/Admin';
import { ReactNode } from 'react';
import { GetServerSidePropsContext } from 'next';
import { getSession } from 'next-auth/react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Envoyer</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>{/* <CardSettings /> */}</main>
    </>
  );
}

Home.pageOptions = {
  requiresAuth: true,
  getLayout: (children: ReactNode) => <Admin>{children}</Admin>,
};

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    redirect: {
      destination: '/auth/login',
      permanent: true,
    },
  };
}
