export const Languages_list = [
  {label: "Afrikaans", value: "af"},
  {label: "Albanian - shqip", value: "sq"},
  {label: "Amharic - አማርኛ", value: "am"},
  {label: "Arabic - العربية", value: "ar"},
  {label: "Aragonese - aragonés", value: "an"},
  {label: "Armenian - հայերեն", value: "hy"},
  {label: "Asturian - asturianu", value: "ast"},
  {label: "Azerbaijani - azərbaycan dili", value: "az"},
  {label: "Basque - euskara", value: "eu"},
  {label: "Belarusian - беларуская", value: "be"},
  {label: "Bengali - বাংলা", value: "bn"},
  {label: "Bosnian - bosanski", value: "bs"},
  {label: "Breton - brezhoneg", value: "br"},
  {label: "Bulgarian - български", value: "bg"},
  {label: "Catalan - català", value: "ca"},
  {label: "Central Kurdish - کوردی (دەستنوسی عەرەبی)", value: "ckb"},
  {label: "Chinese - 中文", value: "zh"},
  {label: "Chinese (Hong Kong) - 中文（香港）", value: "zh-HK"},
  {label: "Chinese (Simplified) - 中文（简体）", value: "zh-CN"},
  {label: "Chinese (Traditional) - 中文（繁體）", value: "zh-TW"},
  {label: "Corsican", value: "co"},
  {label: "Croatian - hrvatski", value: "hr"},
  {label: "Czech - čeština", value: "cs"},
  {label: "Danish - dansk", value: "da"},
  {label: "Dutch - Nederlands", value: "nl"},
  {label: "English", value: "en"},
  {label: "English (Australia)", value: "en-AU"},
  {label: "English (Canada)", value: "en-CA"},
  {label: "English (India)", value: "en-IN"},
  {label: "English (New Zealand)", value: "en-NZ"},
  {label: "English (South Africa)", value: "en-ZA"},
  {label: "English (United Kingdom)", value: "en-GB"},
  {label: "English (United States)", value: "en-US"},
  {label: "Esperanto - esperanto", value: "eo"},
  {label: "Estonian - eesti", value: "et"},
  {label: "Faroese - føroyskt", value: "fo"},
  {label: "Filipino", value: "fil"},
  {label: "Finnish - suomi", value: "fi"},
  {label: "French - français", value: "fr"},
  {label: "French (Canada) - français (Canada)", value: "fr-CA"},
  {label: "French (France) - français (France)", value: "fr-FR"},
  {label: "French (Switzerland) - français (Suisse)", value: "fr-CH"},
  {label: "Galician - galego", value: "gl"},
  {label: "Georgian - ქართული", value: "ka"},
  {label: "German - Deutsch", value: "de"},
  {label: "German (Austria) - Deutsch (Österreich)", value: "de-AT"},
  {label: "German (Germany) - Deutsch (Deutschland)", value: "de-DE"},
  {label: "German (Liechtenstein) - Deutsch (Liechtenstein)", value: "de-LI"},
  {label: "German (Switzerland) - Deutsch (Schweiz)", value: "de-CH"},
  {label: "Greek - Ελληνικά", value: "el"},
  {label: "Guarani", value: "gn"},
  {label: "Gujarati - ગુજરાતી", value: "gu"},
  {label: "Hausa", value: "ha"},
  {label: "Hawaiian - ʻŌlelo Hawaiʻi", value: "haw"},
  {label: "Hebrew - עברית", value: "he"},
  {label: "Hindi - हिन्दी", value: "hi"},
  {label: "Hungarian - magyar", value: "hu"},
  {label: "Icelandic - íslenska", value: "is"},
  {label: "Indonesian - Indonesia", value: "id"},
  {label: "Interlingua", value: "ia"},
  {label: "Irish - Gaeilge", value: "ga"},
  {label: "Italian - italiano", value: "it"},
  {label: "Italian (Italy) - italiano (Italia)", value: "it-IT"},
  {label: "Italian (Switzerland) - italiano (Svizzera)", value: "it-CH"},
  {label: "Japanese - 日本語", value: "ja"},
  {label: "Kannada - ಕನ್ನಡ", value: "kn"},
  {label: "Kazakh - қазақ тілі", value: "kk"},
  {label: "Khmer - ខ្មែរ", value: "km"},
  {label: "Korean - 한국어", value: "ko"},
  {label: "Kurdish - Kurdî", value: "ku"},
  {label: "Kyrgyz - кыргызча", value: "ky"},
  {label: "Lao - ລາວ", value: "lo"},
  {label: "Latin", value: "la"},
  {label: "Latvian - latviešu", value: "lv"},
  {label: "Lingala - lingála", value: "ln"},
  {label: "Lithuanian - lietuvių", value: "lt"},
  {label: "Macedonian - македонски", value: "mk"},
  {label: "Malay - Bahasa Melayu", value: "ms"},
  {label: "Malayalam - മലയാളം", value: "ml"},
  {label: "Maltese - Malti", value: "mt"},
  {label: "Marathi - मराठी", value: "mr"},
  {label: "Mongolian - монгол", value: "mn"},
  {label: "Nepali - नेपाली", value: "ne"},
  {label: "Norwegian - norsk", value: "no"},
  {label: "Norwegian Bokmål - norsk bokmål", value: "nb"},
  {label: "Norwegian Nynorsk - nynorsk", value: "nn"},
  {label: "Occitan", value: "oc"},
  {label: "Oriya - ଓଡ଼ିଆ", value: "or"},
  {label: "Oromo - Oromoo", value: "om"},
  {label: "Pashto - پښتو", value: "ps"},
  {label: "Persian - فارسی", value: "fa"},
  {label: "Polish - polski", value: "pl"},
  {label: "Portuguese - português", value: "pt"},
  {label: "Portuguese (Brazil) - português (Brasil)", value: "pt-BR"},
  {label: "Portuguese (Portugal) - português (Portugal)", value: "pt-PT"},
  {label: "Punjabi - ਪੰਜਾਬੀ", value: "pa"},
  {label: "Quechua", value: "qu"},
  {label: "Romanian - română", value: "ro"},
  {label: "Romanian (Moldova) - română (Moldova)", value: "mo"},
  {label: "Romansh - rumantsch", value: "rm"},
  {label: "Russian - русский", value: "ru"},
  {label: "Scottish Gaelic", value: "gd"},
  {label: "Serbian - српски", value: "sr"},
  {label: "Serbo - Croatian", value: "sh"},
  {label: "Shona - chiShona", value: "sn"},
  {label: "Sindhi", value: "sd"},
  {label: "Sinhala - සිංහල", value: "si"},
  {label: "Slovak - slovenčina", value: "sk"},
  {label: "Slovenian - slovenščina", value: "sl"},
  {label: "Somali - Soomaali", value: "so"},
  {label: "Southern Sotho", value: "st"},
  {label: "Spanish - español", value: "es"},
  {label: "Spanish (Argentina) - español (Argentina)", value: "es-AR"},
  {label: "Spanish (Latin America) - español (Latinoamérica)", value: "es-419"},
  {label: "Spanish (Mexico) - español (México)", value: "es-MX"},
  {label: "Spanish (Spain) - español (España)", value: "es-ES"},
  {label: "Spanish (United States) - español (Estados Unidos)", value: "es-US"},
  {label: "Sundanese", value: "su"},
  {label: "Swahili - Kiswahili", value: "sw"},
  {label: "Swedish - svenska", value: "sv"},
  {label: "Tajik - тоҷикӣ", value: "tg"},
  {label: "Tamil - தமிழ்", value: "ta"},
  {label: "Tatar", value: "tt"},
  {label: "Telugu - తెలుగు", value: "te"},
  {label: "Thai - ไทย", value: "th"},
  {label: "Tigrinya - ትግርኛ", value: "ti"},
  {label: "Tongan - lea fakatonga", value: "to"},
  {label: "Turkish - Türkçe", value: "tr"},
  {label: "Turkmen", value: "tk"},
  {label: "Twi", value: "tw"},
  {label: "Ukrainian - українська", value: "uk"},
  {label: "Urdu - اردو", value: "ur"},
  {label: "Uyghur", value: "ug"},
  {label: "Uzbek - o‘zbek", value: "uz"},
  {label: "Vietnamese - Tiếng Việt", value: "vi"},
  {label: "Walloon - wa", value: "wa"},
  {label: "Welsh - Cymraeg", value: "cy"},
  {label: "Western Frisian", value: "fy"},
  {label: "Xhosa", value: "xh"},
  {label: "Yiddish", value: "yi"},
  {label: "Yoruba - Èdè Yorùbá", value: "yo"},
  {label: "Zulu - isiZulu", value: "zu"}
];

// All countries
// length 252
export const Mobile_code = [
  {label: "Afghanistan",value: 93},
  {label: "Aland Islands",value: 358},
  {label: "Albania",value: 355},
  {label: "Algeria",value: 213},
  {label: "American Samoa",value: 1684},
  {label: "Andorra",value: 376},
  {label: "Angola",value: 244},
  {label: "Anguilla",value: 1264},
  {label: "Antarctica",value: 672},
  {label: "Antigua and Barbuda",value: 1268},
  {label: "Argentina",value: 54},
  {label: "Armenia",value: 374},
  {label: "Aruba",value: 297},
  {label: "Australia",value: 61},
  {label: "Austria",value: 43},
  {label: "Azerbaijan",value: 994},
  {label: "Bahamas",value: 1242},
  {label: "Bahrain",value: 973},
  {label: "Bangladesh",value: 880},
  {label: "Barbados",value: 1246},
  {label: "Belarus",value: 375},
  {label: "Belgium",value: 32},
  {label: "Belize",value: 501},
  {label: "Benin",value: 229},
  {label: "Bermuda",value: 1441},
  {label: "Bhutan",value: 975},
  {label: "Bolivia",value: 591},
  {label: "Bonaire, Sint Eustatius and Saba",value: 599},
  {label: "Bosnia and Herzegovina",value: 387},
  {label: "Botswana",value: 267},
  {label: "Bouvet Island",value: 55},
  {label: "Brazil",value: 55},
  {label: "British Indian Ocean Territory",value: 246},
  {label: "Brunei Darussalam",value: 673},
  {label: "Bulgaria",value: 359},
  {label: "Burkina Faso",value: 226},
  {label: "Burundi",value: 257},
  {label: "Cambodia",value: 855},
  {label: "Cameroon",value: 237},
  {label: "Canada",value: 1},
  {label: "Cape Verde",value: 238},
  {label: "Cayman Islands",value: 1345},
  {label: "Central African Republic",value: 236},
  {label: "Chad",value: 235},
  {label: "Chile",value: 56},
  {label: "China",value: 86},
  {label: "Christmas Island",value: 61},
  {label: "Cocos (Keeling) Islands",value: 672},
  {label: "Colombia",value: 57},
  {label: "Comoros",value: 269},
  {label: "Congo",value: 242},
  {label: "Congo, Democratic Republic of the Congo",value: 242},
  {label: "Cook Islands",value: 682},
  {label: "Costa Rica",value: 506},
  {label: "Cote D'Ivoire",value: 225},
  {label: "Croatia",value: 385},
  {label: "Cuba",value: 53},
  {label: "Curacao",value: 599},
  {label: "Cyprus",value: 357},
  {label: "Czech Republic",value: 420},
  {label: "Denmark",value: 45},
  {label: "Djibouti",value: 253},
  {label: "Dominica",value: 1767},
  {label: "Dominican Republic",value: 1809},
  {label: "Ecuador",value: 593},
  {label: "Egypt",value: 20},
  {label: "El Salvador",value: 503},
  {label: "Equatorial Guinea",value: 240},
  {label: "Eritrea",value: 291},
  {label: "Estonia",value: 372},
  {label: "Ethiopia",value: 251},
  {label: "Falkland Islands (Malvinas)",value: 500},
  {label: "Faroe Islands",value: 298},
  {label: "Fiji",value: 679},
  {label: "Finland",value: 358},
  {label: "France",value: 33},
  {label: "French Guiana",value: 594},
  {label: "French Polynesia",value: 689},
  {label: "French Southern Territories",value: 262},
  {label: "Gabon",value: 241},
  {label: "Gambia",value: 220},
  {label: "Georgia",value: 995},
  {label: "Germany",value: 49},
  {label: "Ghana",value: 233},
  {label: "Gibraltar",value: 350},
  {label: "Greece",value: 30},
  {label: "Greenland",value: 299},
  {label: "Grenada",value: 1473},
  {label: "Guadeloupe",value: 590},
  {label: "Guam",value: 1671},
  {label: "Guatemala",value: 502},
  {label: "Guernsey",value: 44},
  {label: "Guinea",value: 224},
  {label: "Guinea-Bissau",value: 245},
  {label: "Guyana",value: 592},
  {label: "Haiti",value: 509},
  {label: "Heard Island and McDonald Islands",value: 0},
  {label: "Holy See (Vatican City State)",value: 39},
  {label: "Honduras",value: 504},
  {label: "Hong Kong",value: 852},
  {label: "Hungary",value: 36},
  {label: "Iceland",value: 354},
  {label: "India",value: 91},
  {label: "Indonesia",value: 62},
  {label: "Iran, Islamic Republic of",value: 98},
  {label: "Iraq",value: 964},
  {label: "Ireland",value: 353},
  {label: "Isle of Man",value: 44},
  {label: "Israel",value: 972},
  {label: "Italy",value: 39},
  {label: "Jamaica",value: 1876},
  {label: "Japan",value: 81},
  {label: "Jersey",value: 44},
  {label: "Jordan",value: 962},
  {label: "Kazakhstan",value: 7},
  {label: "Kenya",value: 254},
  {label: "Kiribati",value: 686},
  {label: "Korea, Democratic People's Republic of",value: 850},
  {label: "Korea, Republic of",value: 82},
  {label: "Kosovo",value: 381},
  {label: "Kuwait",value: 965},
  {label: "Kyrgyzstan",value: 996},
  {label: "Lao People's Democratic Republic",value: 856},
  {label: "Latvia",value: 371},
  {label: "Lebanon",value: 961},
  {label: "Lesotho",value: 266},
  {label: "Liberia",value: 231},
  {label: "Libyan Arab Jamahiriya",value: 218},
  {label: "Liechtenstein",value: 423},
  {label: "Lithuania",value: 370},
  {label: "Luxembourg",value: 352},
  {label: "Macao",value: 853},
  {label: "Macedonia, the Former Yugoslav Republic of",value: 389},
  {label: "Madagascar",value: 261},
  {label: "Malawi",value: 265},
  {label: "Malaysia",value: 60},
  {label: "Maldives",value: 960},
  {label: "Mali",value: 223},
  {label: "Malta",value: 356},
  {label: "Marshall Islands",value: 692},
  {label: "Martinique",value: 596},
  {label: "Mauritania",value: 222},
  {label: "Mauritius",value: 230},
  {label: "Mayotte",value: 262},
  {label: "Mexico",value: 52},
  {label: "Micronesia, Federated States of",value: 691},
  {label: "Moldova, Republic of",value: 373},
  {label: "Monaco",value: 377},
  {label: "Mongolia",value: 976},
  {label: "Montenegro",value: 382},
  {label: "Montserrat",value: 1664},
  {label: "Morocco",value: 212},
  {label: "Mozambique",value: 258},
  {label: "Myanmar",value: 95},
  {label: "Namibia",value: 264},
  {label: "Nauru",value: 674},
  {label: "Nepal",value: 977},
  {label: "Netherlands",value: 31},
  {label: "Netherlands Antilles",value: 599},
  {label: "New Caledonia",value: 687},
  {label: "New Zealand",value: 64},
  {label: "Nicaragua",value: 505},
  {label: "Niger",value: 227},
  {label: "Nigeria",value: 234},
  {label: "Niue",value: 683},
  {label: "Norfolk Island",value: 672},
  {label: "Northern Mariana Islands",value: 1670},
  {label: "Norway",value: 47},
  {label: "Oman",value: 968},
  {label: "Pakistan",value: 92},
  {label: "Palau",value: 680},
  {label: "Palestinian Territory, Occupied",value: 970},
  {label: "Panama",value: 507},
  {label: "Papua New Guinea",value: 675},
  {label: "Paraguay",value: 595},
  {label: "Peru",value: 51},
  {label: "Philippines",value: 63},
  {label: "Pitcairn",value: 64},
  {label: "Poland",value: 48},
  {label: "Portugal",value: 351},
  {label: "Puerto Rico",value: 1787},
  {label: "Qatar",value: 974},
  {label: "Reunion",value: 262},
  {label: "Romania",value: 40},
  {label: "Russian Federation",value: 7},
  {label: "Rwanda",value: 250},
  {label: "Saint Barthelemy",value: 590},
  {label: "Saint Helena",value: 290},
  {label: "Saint Kitts and Nevis",value: 1869},
  {label: "Saint Lucia",value: 1758},
  {label: "Saint Martin",value: 590},
  {label: "Saint Pierre and Miquelon",value: 508},
  {label: "Saint Vincent and the Grenadines",value: 1784},
  {label: "Samoa",value: 684},
  {label: "San Marino",value: 378},
  {label: "Sao Tome and Principe",value: 239},
  {label: "Saudi Arabia",value: 966},
  {label: "Senegal",value: 221},
  {label: "Serbia",value: 381},
  {label: "Serbia and Montenegro",value: 381},
  {label: "Seychelles",value: 248},
  {label: "Sierra Leone",value: 232},
  {label: "Singapore",value: 65},
  {label: "St Martin",value: 721},
  {label: "Slovakia",value: 421},
  {label: "Slovenia",value: 386},
  {label: "Solomon Islands",value: 677},
  {label: "Somalia",value: 252},
  {label: "South Africa",value: 27},
  {label: "South Georgia and the South Sandwich Islands",value: 500},
  {label: "South Sudan",value: 211},
  {label: "Spain",value: 34},
  {label: "Sri Lanka",value: 94},
  {label: "Sudan",value: 249},
  {label: "Suriname",value: 597},
  {label: "Svalbard and Jan Mayen",value: 47},
  {label: "Swaziland",value: 268},
  {label: "Sweden",value: 46},
  {label: "Switzerland",value: 41},
  {label: "Syrian Arab Republic",value: 963},
  {label: "Taiwan, Province of China",value: 886},
  {label: "Tajikistan",value: 992},
  {label: "Tanzania, United Republic of",value: 255},
  {label: "Thailand",value: 66},
  {label: "Timor-Leste",value: 670},
  {label: "Togo",value: 228},
  {label: "Tokelau",value: 690},
  {label: "Tonga",value: 676},
  {label: "Trinidad and Tobago",value: 1868},
  {label: "Tunisia",value: 216},
  {label: "Turkey",value: 90},
  {label: "Turkmenistan",value: 7370},
  {label: "Turks and Caicos Islands",value: 1649},
  {label: "Tuvalu",value: 688},
  {label: "Uganda",value: 256},
  {label: "Ukraine",value: 380},
  {label: "United Arab Emirates",value: 971},
  {label: "United Kingdom",value: 44},
  {label: "United States",value: 1},
  {label: "United States Minor Outlying Islands",value: 1},
  {label: "Uruguay",value: 598},
  {label: "Uzbekistan",value: 998},
  {label: "Vanuatu",value: 678},
  {label: "Venezuela",value: 58},
  {label: "Viet Nam",value: 84},
  {label: "Virgin Islands, British",value: 1284},
  {label: "Virgin Islands, U.s.",value: 1340},
  {label: "Wallis and Futuna",value: 681},
  {label: "Western Sahara",value: 212},
  {label: "Yemen",value: 967},
  {label: "Zambia",value: 260},
  {label: "Zimbabwe",value: 263}
];